name: vn-maker
recipe: laravel
config:
  php: '8.1'
  via: nginx
  database: mysql
  cache: redis
  xdebug: true
  webroot: ./public
  config:
    php: .lando/php.ini
services:
  database:
    portforward: 3307
